sonar.projectKey=polchduikt_launchly
sonar.organization=polchduikt
sonar.projectName=Launchly
sonar.projectVersion=1.0.0

sonar.sourceEncoding=UTF-8
sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes

# Exclusions
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/build/**,**/coverage/**,**/.lighthouseci/**,**/db/changelog/**,frontend/src/const/templatesData.ts,frontend/e2e/**,**/*.json,**/*.svg,**/*.sql,**/*.md,**/*.properties,**/*.yml,**/*.yaml
sonar.cpd.exclusions=frontend/src/const/templatesData.ts,frontend/e2e/**,**/dto/**,**/entity/**,**/*.test.ts,**/*.test.tsx,**/*Test.java

# JaCoCo Code Coverage
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
