sonar.projectKey=polchduikt_launchly
sonar.organization=polchduikt
sonar.projectName=Launchly
sonar.projectVersion=1.0.1

sonar.sourceEncoding=UTF-8
sonar.sources=backend/src/main/java
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes

# Exclusions
sonar.exclusions=**/dto/**,**/entity/**,**/config/**,**/exception/**,**/db/changelog/**,**/target/**,**/dist/**,**/node_modules/**,**/coverage/**,**/.lighthouseci/**,**/*.json,**/*.svg,**/*.sql,**/*.md,**/*.properties,**/*.yml,**/*.yaml,frontend/**
sonar.cpd.exclusions=**/dto/**,**/entity/**,**/*Test.java

# JaCoCo Code Coverage
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/dto/**,**/entity/**,**/config/**,**/exception/**,**/common/**,**/integration/**,**/ai/**,**/telegram/**,**/util/**,**/scheduler/**,**/executor/**,**/mapper/**,**/service/impl/**
