--liquibase formatted sql

--changeset launchly:056
ALTER TABLE bots ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
