import { t } from '../i18n/config';
import {
  MessageSquare,
  GitFork,
  Sliders,
  Code,
  Clock,
  Shuffle,
  StickyNote,
  Power,
  SquareArrowRight,
  Terminal,
  Calculator,
  Trophy,
} from 'lucide-react';

export const STEP_OPTION_GROUPS = [
  {
    id: 'messaging',
    titleKey: 'flow_builder.cat_messaging',
    defaultTitle: 'Повідомлення',
    types: ['MESSAGE'],
  },
  {
    id: 'logic',
    titleKey: 'flow_builder.cat_logic',
    defaultTitle: 'Логіка та затримки',
    types: ['CONDITION', 'RANDOMIZER', 'SMART_DELAY', 'COOLDOWN'],
  },
  {
    id: 'operations',
    titleKey: 'flow_builder.cat_operations',
    defaultTitle: 'Операції та рейтинг',
    types: ['ACTION', 'MATH', 'LEADERBOARD'],
  },
  {
    id: 'integrations',
    titleKey: 'flow_builder.cat_integrations',
    defaultTitle: 'Інтеграції',
    types: ['API_CALL', 'START_AUTOMATION'],
  },
  {
    id: 'utilities',
    titleKey: 'flow_builder.cat_utilities',
    defaultTitle: 'Службові',
    types: ['COMMAND', 'COMMENT', 'END'],
  },
];

export const STEP_OPTIONS = [
  {
    type: 'MESSAGE',
    get label() { return t('step_option.MESSAGE.label'); },
    get description() { return t('step_option.MESSAGE.desc'); },
    icon: MessageSquare,
    color: 'text-sky-500 bg-sky-50 border-sky-100',
  },
  {
    type: 'CONDITION',
    get label() { return t('step_option.CONDITION.label'); },
    get description() { return t('step_option.CONDITION.desc'); },
    icon: GitFork,
    color: 'text-purple-600 bg-purple-50 border-purple-100',
  },
  {
    type: 'ACTION',
    get label() { return t('step_option.ACTION.label'); },
    get description() { return t('step_option.ACTION.desc'); },
    icon: Sliders,
    color: 'text-amber-600 bg-amber-50 border-amber-100',
  },
  {
    type: 'MATH',
    get label() { return t('step_option.MATH.label', 'Calculation'); },
    get description() { return t('step_option.MATH.desc', 'Random or static points calculation and score management'); },
    icon: Calculator,
    color: 'text-cyan-600 bg-cyan-50 border-cyan-100',
  },
  {
    type: 'LEADERBOARD',
    get label() { return t('step_option.LEADERBOARD.label', 'Leaderboard'); },
    get description() { return t('step_option.LEADERBOARD.desc', 'Rank users and generate leaderboard list text'); },
    icon: Trophy,
    color: 'text-fuchsia-600 bg-fuchsia-50 border-fuchsia-100',
  },
  {
    type: 'COOLDOWN',
    get label() { return t('step_option.COOLDOWN.label', 'Cooldown'); },
    get description() { return t('step_option.COOLDOWN.desc', 'Limit action frequency and send timeout warning'); },
    icon: Clock,
    color: 'text-amber-600 bg-amber-50 border-amber-100',
  },
  {
    type: 'API_CALL',
    get label() { return t('step_option.API_CALL.label'); },
    get description() { return t('step_option.API_CALL.desc'); },
    icon: Code,
    color: 'text-indigo-500 bg-indigo-50 border-indigo-100',
  },
  {
    type: 'SMART_DELAY',
    get label() { return t('step_option.SMART_DELAY.label'); },
    get description() { return t('step_option.SMART_DELAY.desc'); },
    icon: Clock,
    color: 'text-rose-500 bg-rose-50 border-rose-100',
  },
  {
    type: 'RANDOMIZER',
    get label() { return t('step_option.RANDOMIZER.label'); },
    get description() { return t('step_option.RANDOMIZER.desc'); },
    icon: Shuffle,
    color: 'text-purple-650 bg-purple-50 border-purple-100',
  },
  {
    type: 'START_AUTOMATION',
    get label() { return t('step_option.START_AUTOMATION.label'); },
    get description() { return t('step_option.START_AUTOMATION.desc'); },
    icon: SquareArrowRight,
    color: 'text-lime-600 bg-lime-50 border-lime-100',
  },
  {
    type: 'COMMAND',
    get label() { return t('step_option.COMMAND.label'); },
    get description() { return t('step_option.COMMAND.desc'); },
    icon: Terminal,
    color: 'text-teal-600 bg-teal-50 border-teal-100',
  },
  {
    type: 'COMMENT',
    get label() { return t('step_option.COMMENT.label'); },
    get description() { return t('step_option.COMMENT.desc'); },
    icon: StickyNote,
    color: 'text-amber-500 bg-amber-50 border-amber-100',
  },
  {
    type: 'END',
    get label() { return t('step_option.END.label'); },
    get description() { return t('step_option.END.desc'); },
    icon: Power,
    color: 'text-slate-500 bg-slate-50 border-slate-100',
  },
];
