export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  OAUTH_CALLBACK: '/oauth2/callback',
  HOME: '/home',
  DASHBOARD: '/dashboard',
  CONNECT_BOT: '/connect-bot',
  AUTOMATIONS: '/automations',
  SETTINGS: '/settings',
  FLOW_BUILDER: '/builder',
  CHAT: '/chat',
  CONTACTS: '/contacts',
  AI: '/ai',
  ORDERS: '/orders',
  BROADCASTS: '/broadcasts',
  BROADCAST_BUILDER: '/broadcasts/:id',
  INTEGRATIONS: '/integrations',
  BILLING_SUCCESS: '/billing/success',
  BILLING_CANCEL: '/billing/cancel',
  BLOG: '/blog',
  BLOG_DETAIL: '/blog/:id',
  BLOCKED: '/blocked',
  ADMIN_HOME: '/admin',
  ADMIN_STATS: '/admin/stats',
  ADMIN_CHATS: '/admin/chats',
  ADMIN_USERS: '/admin/users',
  ADMIN_AUTOMATIONS: '/admin/automations',
  ADMIN_BROADCASTS: '/admin/broadcasts',
  ADMIN_LOGS: '/admin/logs',
};

