export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  OAUTH_CALLBACK: '/oauth2/callback',
  HOME: '/home',
  CONNECT_BOT: '/connect-bot',
  AUTOMATIONS: '/automations',
  SETTINGS: '/settings',
  FLOW_BUILDER: '/builder',
  CHAT: '/chat',
  CONTACTS: '/contacts',
  ORDERS: '/orders',
  BROADCASTS: '/broadcasts',
  BROADCAST_BUILDER: '/broadcasts/:id',
  INTEGRATIONS: '/integrations',
  BILLING_SUCCESS: '/billing/success',
  BILLING_CANCEL: '/billing/cancel',
};

